version: '3.8'

services:
  crypto-toolbox-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_toolbox_web_container
    restart: unless-stopped
    networks: 
      - proxy-network
 networks:
  proxy-network:
    external: true
