version: '3.8'

services:
  crypto-toolbox-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_toolbox_web_container
    ports:
      - "7823:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
    restart: unless-stopped
